//Artist,Title,Album,Genre,Time,file],

var music = [
["Coupons","Driving to your House Party (Remix)","Driving to Your House Party","Retrowave",363,],
["Garth Knight","AutoTron (Remaster)","Goliath","Retrowave",297],
["Jasper Byrne","Miami","Hotline Miami - EP","Retrowave",278],
["Lazerhawk","Star Hustler","Visitors","Retrowave",299],
["M.O.O.N.","Paris","M.O.O.N. - EP","Retrowave",275],
["Super Radical","Savage Streets","Savage Streets - Single","Retrowave",298],
["Flamingosis","Flight of the Flamingo","Bright Moments","Vaporwave",189],
["Heavy Systems, Inc.","Ill Terminal","Ill Terminal - Single","Vaporwave",182],
["Lindsheaven Virtual Plaza","Weather Scanning","NTSC  Memories","Vaporwave",261],
["Master Stryker","Sony Boogie","Master Stryker Discography 2014 - 2015","Vaporwave",148],
["Thoughts","Midnight","Midnight - Single","Vaporwave",163],
["Topaz Gang","Work","Tuxedo Princess","Vaporwave",77],
["bsd.u","and.i.smoke","late night bumps 3","LoFi Hip Hop",126],
["bsd.u","doe or die","late night bumps 1","LoFi Hip Hop",73],
["bsd.u","hoodie weather","late night bumps 3","LoFi Hip Hop",128],
["gnosis","hot.days cold.nights","hot.days cold.nights - single","LoFi Hip Hop",74],
["Onra","I Wanna Go Back","Chinoiseries","LoFi Hip Hop",196],
["Swarvy","Kittylitter","Scotch","LoFi Hip Hop",214],
["A-Trak ft. GTA","Landline 2.0","Tuna Melt","Trap",254],
["FruitSnacks","Heat","Heat - Single","Trap",217],
["gLAdiator x Chromatic","GameCube Nintendo","GameCube Nintendo - Single","Trap",203],
["Hati","Evilpiece","Evilpiece - Single","Trap",119],
["Hucci","Mafia","Rose Gold","Trap",267],
["N.A.S.A. ft. Aynzli Jones","Hide (Tropkillaz Remix)","Hide - Single","Trap",205],
["The Celestics","Charles Barkley","Supreme Laziness","Underground Hip Hop",243],
["Chops","My Rims","Ping Pong Playa (Original Soundtrack)","Underground Hip Hop",229],
["De La Soul ft. 2Chainz","Whoodeeni","and the Anonymous Nobody...","Underground Hip Hop",275],
["Evidence","Late for the Sky","Raining Cats and Dogs","Underground Hip Hop",342],
["Little Brother","They Way You Do It (Phoniks Remix)","The Way You Do It (Remix) - Single","Underground Hip Hop",173],
["The Underachievers","Gold Soul Theory","INDIGOISM","Underground Hip Hop",186],
["Benorno","Beats Train","Beats Train - Single","Boombap",235],
["Brock Berrigan","The Way It Goes","Chapter 10","Boombap",173],
["Chill Bump","The Memo","Ego Trip","Boombap",186],
["Chinese Man","Run Run Run (Chill Bump Remix)","Sho-Bro","Boombap",225],
["Grolok","Decouverte","Decouverte - Single","Boombap",143],
["Jesse James","Harikiri","Monochrome Skies","Boombap",403]
];